[server]
host: 0.0.0.0
port: 7125
max_upload_size: 1024
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

[file_manager]
# post processing for object cancel. Not recommended for low resource SBCs such as a Pi Zero. Default False
enable_object_processing: True

[authorization]
cors_domains:
   https://my.mainsail.xyz
    http://my.mainsail.xyz
    http://*.local
    http://*.lan
trusted_clients:
    192.168.1.104
    192.168.1.102
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128


[octoprint_compat]

[history]

[announcements]
subscriptions:
    mainsail


[update_manager]
channel: dev
refresh_interval: 168
enable_auto_refresh: True

[update_manager mainsail]
path: /home/pi/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json

[update_manager mainsail-config]
managed_services: klipper
origin: https://github.com/mainsail-crew/mainsail-config.git
path: /home/pi/mainsail-config
primary_branch: master
type: git_repo

[update_manager KlipperScreen]
install_script: /home/pi/KlipperScreen/scripts/KlipperScreen-install.sh
requirements: /home/pi/KlipperScreen/scripts/KlipperScreen-requirements.txt
env: /home/pi/.KlipperScreen-env/bin/python
managed_services: KlipperScreen
origin: https://github.com/KlipperScreen/KlipperScreen.git
path: /home/pi/KlipperScreen
type: git_repo

[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

[timelapse]
enabled: True
#verbose: True
## 영상이 최종 저장될 곳 (메인세일에서 바로 보임)
output_path: ~/printer_data/timelapse/
## 촬영 중 임시 사진이 저장될 곳
frame_path: /tmp/timelapse/printer
## ffmpeg 경로는 그대로 두시면 됩니다
ffmpeg_binary_path: /usr/bin/ffmpeg

# Crowsnest update_manager entry
[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh

# Sonar update_manager entry
[update_manager sonar]
type: git_repo
path: ~/sonar
origin: https://github.com/mainsail-crew/sonar.git
primary_branch: main
managed_services: sonar
install_script: tools/install.sh


[update_manager led_effect]
type: git_repo
path: ~/klipper-led_effect
origin: https://github.com/julianschill/klipper-led_effect.git
is_system_service: False

[update_manager cartographer_plugin]
type: python
channel: stable
virtualenv: ~/klippy-env
project_name: cartographer3d-plugin
is_system_service: False
managed_services: klipper
info_tags: desc=Cartographer Plugin


[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main

[include octoeverywhere-system.cfg]

#[include moonraker-obico-update.cfg]
